import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export type ReportLang = "en" | "de";

type CompanyInfo = {
  name: string | null;
  address: string | null;
  phone: string | null;
  /** Base64 data URL (data:image/jpeg;base64,...) or null if no logo/couldn't load it. */
  logoDataUrl: string | null;
  /** Only passed when the manager is on Business plan — otherwise report stays plain black/white. */
  brandColor: string | null;
};

type ReportStats = {
  total: number;
  resolved: number;
  slaCompliance: number;
};

type SnagRow = {
  location: string;
  category: string;
  priority: string;
  status: string;
  created_at: string;
  deadline_at: string | null;
  description: string;
  notes: string | null;
  assignedTo: string | null;
  /** Pre-resolved base64 data URLs — the generator never fetches anything itself. */
  beforePhotoDataUrl: string | null;
  afterPhotoDataUrl: string | null;
};

// Report-only strings — separate from the app's UI i18n files since these
// never appear in the app itself, only inside the generated document.
const STRINGS: Record<ReportLang, Record<string, string>> = {
  en: {
    title: "Site Snag Report",
    period: "Report period",
    generatedOn: "Generated on",
    summary: "Summary",
    totalSnags: "Total snags",
    resolved: "Resolved",
    slaCompliance: "SLA compliance",
    resolutionRate: "Resolution rate",
    snagDetails: "Snag Details",
    assigned: "Assigned",
    deadline: "Deadline",
    notes: "Notes",
    before: "Before",
    after: "After",
    noSnags: "No snags recorded.",
    footer: "Generated by SnapSnag",
    page: "Page",
    of: "of",
    unassigned: "Unassigned",
  },
  de: {
    title: "Baustellen-Mängelbericht",
    period: "Berichtszeitraum",
    generatedOn: "Erstellt am",
    summary: "Zusammenfassung",
    totalSnags: "Mängel gesamt",
    resolved: "Behoben",
    slaCompliance: "SLA-Einhaltung",
    resolutionRate: "Behebungsquote",
    snagDetails: "Mängel im Detail",
    assigned: "Zugewiesen",
    deadline: "Frist",
    notes: "Notizen",
    before: "Vorher",
    after: "Nachher",
    noSnags: "Keine Mängel erfasst.",
    footer: "Erstellt mit SnapSnag",
    page: "Seite",
    of: "von",
    unassigned: "Nicht zugewiesen",
  },
};

// A generic placeholder for fields that are legitimately empty (no
// deadline set, nobody assigned yet) — clearer on a printed page than
// leaving blank space, without literally printing the word "null".
const EMPTY = "\u2014"; // —

// Category/priority/status values are stored in English in the DB
// regardless of UI language, so translate them for display in a German
// report — these mirror the same terms used in src/locales/de.json.
const CATEGORY_DE: Record<string, string> = {
  Structural: "Baulich",
  Electrical: "Elektrik",
  Plumbing: "Sanitär",
  Finishing: "Ausbau",
  Safety: "Sicherheit",
};
const PRIORITY_DE: Record<string, string> = {
  Critical: "Kritisch",
  High: "Hoch",
  Medium: "Mittel",
  Low: "Niedrig",
};
const STATUS_DE: Record<string, string> = { Open: "Offen", Fixed: "Behoben" };

const PRIORITY_COLORS: Record<string, [number, number, number]> = {
  Critical: [239, 68, 68],
  High: [249, 115, 22],
  Medium: [234, 179, 8],
  Low: [34, 197, 94],
};
const STATUS_COLORS: Record<string, [number, number, number]> = {
  Open: [239, 68, 68],
  Fixed: [34, 197, 94],
};

function localize(
  lang: ReportLang,
  field: "category" | "priority" | "status",
  value: string,
) {
  if (lang !== "de") return value;
  const table =
    field === "category"
      ? CATEGORY_DE
      : field === "priority"
        ? PRIORITY_DE
        : STATUS_DE;
  return table[value] ?? value;
}

function hexToRgb(hex: string): [number, number, number] {
  const m = /^#?([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i.exec(hex);
  if (!m) return [232, 80, 10]; // fallback: SnapSnag orange
  return [parseInt(m[1], 16), parseInt(m[2], 16), parseInt(m[3], 16)];
}

export function generateSnagReportPdf(params: {
  lang: ReportLang;
  company: CompanyInfo;
  periodStart: Date;
  periodEnd: Date;
  stats: ReportStats;
  snags: SnagRow[];
}): Blob {
  const { lang, company, periodStart, periodEnd, stats, snags } = params;
  const s = STRINGS[lang];
  const locale = lang === "de" ? "de-DE" : "en-US";
  const [r, g, b] = hexToRgb(company.brandColor ?? "#E8500A");

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 16;
  const footerZone = 14; // reserved space at bottom of every page for the footer
  let y = margin;

  /** Starts a new page (without drawing the footer yet — that happens once, at the end, for every page). */
  function ensureSpace(needed: number) {
    if (y + needed > pageHeight - footerZone) {
      doc.addPage();
      y = margin;
    }
  }

  // ── Letterhead ────────────────────────────────────────────────────────
  const logoSize = 18;
  if (company.logoDataUrl) {
    try {
      doc.addImage(
        company.logoDataUrl,
        "JPEG",
        margin,
        y,
        logoSize,
        logoSize,
        undefined,
        "FAST",
      );
    } catch {
      // Corrupt/unsupported image data — skip the logo rather than fail the whole report.
    }
  }
  const textX = company.logoDataUrl ? margin + logoSize + 6 : margin;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(20, 20, 20);
  doc.text(company.name || "SnapSnag", textX, y + 7);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(90, 90, 90);
  let subY = y + 12;
  if (company.address) {
    doc.text(company.address, textX, subY);
    subY += 4.5;
  }
  if (company.phone) {
    doc.text(company.phone, textX, subY);
  }

  y += logoSize + 6;
  doc.setDrawColor(r, g, b);
  doc.setLineWidth(1);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // ── Title + period ────────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(20, 20, 20);
  doc.text(s.title, margin, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(90, 90, 90);
  doc.text(
    `${s.period}: ${periodStart.toLocaleDateString(locale)} \u2192 ${periodEnd.toLocaleDateString(locale)}`,
    margin,
    y,
  );
  y += 5;
  doc.text(
    `${s.generatedOn}: ${new Date().toLocaleDateString(locale)}`,
    margin,
    y,
  );
  y += 10;

  // ── Summary ───────────────────────────────────────────────────────────
  const resolutionRate =
    stats.total > 0 ? Math.round((stats.resolved / stats.total) * 100) : 0;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(20, 20, 20);
  doc.text(s.summary, margin, y);
  y += 6;

  autoTable(doc, {
    startY: y,
    theme: "grid",
    styles: { fontSize: 9, cellPadding: 3, textColor: [40, 40, 40] },
    headStyles: { fillColor: [r, g, b], textColor: 255, fontStyle: "bold" },
    margin: { left: margin, right: margin },
    head: [[s.totalSnags, s.resolved, s.slaCompliance, s.resolutionRate]],
    body: [
      [
        String(stats.total),
        String(stats.resolved),
        `${stats.slaCompliance}%`,
        `${resolutionRate}%`,
      ],
    ],
  });

  y =
    (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable
      ?.finalY ?? y + 20;
  y += 10;

  // ── Snag details (one card per snag — photos need real layout space,
  //    so this is hand-drawn rather than another autoTable) ─────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(20, 20, 20);
  ensureSpace(10);
  doc.text(s.snagDetails, margin, y);
  y += 7;

  if (snags.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text(s.noSnags, margin, y);
  }

  const contentWidth = pageWidth - margin * 2;
  const photoSize = 30;

  for (const snag of snags) {
    // Rough height estimate up-front so the whole card page-breaks together
    // rather than splitting mid-card.
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    const descLines = doc.splitTextToSize(
      snag.description || EMPTY,
      contentWidth,
    );
    const notesLines = snag.notes
      ? doc.splitTextToSize(snag.notes, contentWidth)
      : [];
    const hasPhotos = !!(snag.beforePhotoDataUrl || snag.afterPhotoDataUrl);
    const estHeight =
      7 + // location/badges line
      5 + // meta line (category/assigned/deadline)
      descLines.length * 4 +
      (notesLines.length ? notesLines.length * 4 + 2 : 0) +
      (hasPhotos ? photoSize + 8 : 0) +
      6; // divider + gap

    ensureSpace(estHeight);

    // Location + priority/status badges
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10.5);
    doc.setTextColor(20, 20, 20);
    doc.text(snag.location, margin, y);

    const priorityColor = PRIORITY_COLORS[snag.priority] ?? [120, 120, 120];
    const statusColor = STATUS_COLORS[snag.status] ?? [120, 120, 120];
    const priorityLabel = localize(lang, "priority", snag.priority);
    const statusLabel = localize(lang, "status", snag.status);
    doc.setFontSize(9);
    const statusWidth = doc.getTextWidth(statusLabel);
    doc.setTextColor(...statusColor);
    doc.text(statusLabel, pageWidth - margin - statusWidth, y);
    const priorityWidth = doc.getTextWidth(priorityLabel);
    doc.setTextColor(...priorityColor);
    doc.text(
      priorityLabel,
      pageWidth - margin - statusWidth - 6 - priorityWidth,
      y,
    );
    y += 5;

    // Meta line: category · assigned · deadline
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(90, 90, 90);
    const deadlineText = snag.deadline_at
      ? new Date(snag.deadline_at).toLocaleDateString(locale)
      : EMPTY;
    const assignedText = snag.assignedTo || s.unassigned;
    doc.text(
      `${localize(lang, "category", snag.category)}   \u00b7   ${s.assigned}: ${assignedText}   \u00b7   ${s.deadline}: ${deadlineText}`,
      margin,
      y,
    );
    y += 5;

    // Description
    doc.setFontSize(9);
    doc.setTextColor(40, 40, 40);
    doc.text(descLines, margin, y);
    y += descLines.length * 4 + 2;

    // Notes (optional)
    if (notesLines.length) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(8.5);
      doc.setTextColor(110, 110, 110);
      doc.text(`${s.notes}: `, margin, y);
      const notesLabelWidth = doc.getTextWidth(`${s.notes}: `);
      doc.text(notesLines, margin + notesLabelWidth, y);
      y += notesLines.length * 4 + 2;
    }

    // Before/after photos
    if (hasPhotos) {
      let photoX = margin;
      if (snag.beforePhotoDataUrl) {
        try {
          doc.addImage(
            snag.beforePhotoDataUrl,
            "JPEG",
            photoX,
            y,
            photoSize,
            photoSize,
            undefined,
            "FAST",
          );
          doc.setFont("helvetica", "normal");
          doc.setFontSize(7.5);
          doc.setTextColor(120, 120, 120);
          doc.text(s.before, photoX, y + photoSize + 3.5);
        } catch {
          // skip a corrupt/unsupported photo rather than fail the report
        }
        photoX += photoSize + 6;
      }
      if (snag.afterPhotoDataUrl) {
        try {
          doc.addImage(
            snag.afterPhotoDataUrl,
            "JPEG",
            photoX,
            y,
            photoSize,
            photoSize,
            undefined,
            "FAST",
          );
          doc.setFont("helvetica", "normal");
          doc.setFontSize(7.5);
          doc.setTextColor(120, 120, 120);
          doc.text(s.after, photoX, y + photoSize + 3.5);
        } catch {
          // skip
        }
      }
      y += photoSize + 8;
    }

    // Divider between cards
    doc.setDrawColor(225, 225, 225);
    doc.setLineWidth(0.3);
    doc.line(margin, y, pageWidth - margin, y);
    y += 6;
  }

  // ── Footer (every page) ───────────────────────────────────────────────
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(s.footer, margin, pageHeight - 8);
    doc.text(
      `${s.page} ${i} ${s.of} ${pageCount}`,
      pageWidth - margin,
      pageHeight - 8,
      {
        align: "right",
      },
    );
  }

  return doc.output("blob");
}
